-- MySQL Script generated by MySQL Workbench
-- Wed Dec 15 19:25:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uniShare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uniShare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uniShare` DEFAULT CHARACTER SET utf8 ;
USE `uniShare` ;

-- -----------------------------------------------------
-- Table `uniShare`.`Scuola`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniShare`.`Scuola` ;

CREATE TABLE IF NOT EXISTS `uniShare`.`Scuola` (
  `idScuola` INT NOT NULL AUTO_INCREMENT,
  `nomeScuola` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idScuola`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniShare`.`Insegnamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniShare`.`Insegnamento` ;

CREATE TABLE IF NOT EXISTS `uniShare`.`Insegnamento` (
  `idInsegnamento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `scuola` INT NOT NULL,
  PRIMARY KEY (`idInsegnamento`),
  INDEX `fk_DipartimentoScuola_Scuola1_idx` (`scuola` ASC) ,
  CONSTRAINT `fk_DipartimentoScuola_Scuola1`
    FOREIGN KEY (`scuola`)
    REFERENCES `uniShare`.`Scuola` (`idScuola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniShare`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniShare`.`Users` ;

CREATE TABLE IF NOT EXISTS `uniShare`.`Users` (
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `UserType` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniShare`.`Appunti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniShare`.`Appunti` ;

CREATE TABLE IF NOT EXISTS `uniShare`.`Appunti` (
  `idappunti` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Path` VARCHAR(45) NOT NULL,
  `uploadDate` DATE NOT NULL,
  `price` DOUBLE NOT NULL,
  `insegnamento_scuola` INT NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idappunti`),
  INDEX `fk_Appunti_DipartimentoScuola1_idx` (`insegnamento_scuola` ASC) ,
  INDEX `fk_Appunti_Users1_idx` (`user` ASC) ,
  CONSTRAINT `fk_Appunti_DipartimentoScuola1`
    FOREIGN KEY (`insegnamento_scuola`)
    REFERENCES `uniShare`.`Insegnamento` (`idInsegnamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appunti_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `uniShare`.`Users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniShare`.`Acquisto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniShare`.`Acquisto` ;

CREATE TABLE IF NOT EXISTS `uniShare`.`Acquisto` (
  `ID_acquisto` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `appunto` INT NOT NULL,
  PRIMARY KEY (`ID_acquisto`),
  INDEX `fk_Acquisto_Appunti1_idx` (`appunto` ASC) ,
  CONSTRAINT `fk_Acquisto_Appunti1`
    FOREIGN KEY (`appunto`)
    REFERENCES `uniShare`.`Appunti` (`idappunti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniShare`.`Recensione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniShare`.`Recensione` ;

CREATE TABLE IF NOT EXISTS `uniShare`.`Recensione` (
  `idRecensione` INT NOT NULL AUTO_INCREMENT,
  `valore` INT NOT NULL,
  `appunto` INT NOT NULL,
  `acquisto` INT NOT NULL,
  PRIMARY KEY (`idRecensione`),
  INDEX `fk_Recensione_Appunti1_idx` (`appunto` ASC) ,
  INDEX `fk_Recensione_Acquisto1_idx` (`acquisto` ASC) ,
  CONSTRAINT `fk_Recensione_Appunti1`
    FOREIGN KEY (`appunto`)
    REFERENCES `uniShare`.`Appunti` (`idappunti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recensione_Acquisto1`
    FOREIGN KEY (`acquisto`)
    REFERENCES `uniShare`.`Acquisto` (`ID_acquisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniShare`.`dashboard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uniShare`.`dashboard` ;

CREATE TABLE IF NOT EXISTS `uniShare`.`dashboard` (
  `obj1` INT NOT NULL,
  `obj2` INT NOT NULL,
  `obj3` INT NOT NULL,
  `obj4` INT NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  INDEX `fk_dashboard_Users1_idx` (`user` ASC) ,
  PRIMARY KEY (`user`),
  CONSTRAINT `fk_dashboard_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `uniShare`.`Users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
